anunciar/config/routes.rb
Rails.application.routes.draw do
  get "/application.manifest" => Rails::Offline
  devise_for :admins
  devise_for :students
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :announcements
  root 'announcements#index'
  namespace :api, defaults: {format: 'json'} do
  	namespace :v1 do
  		resources :announcements
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

anunciar/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

anunciar/app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

anunciar/app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_student!
  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all.order("created_at DESC")
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:title, :description, :deadline, :tags)
    end
end

anunciar/app/controllers/api/v1/announcements_controller.rb
module Api
	module V1
		class AnnouncementsController < ApplicationController
			before_action :set_announcement, only: [:show, :edit, :update, :destroy]

			respond_to :json
			def index
				respond_with Announcement.all.order("created_at DESC")
			end
			def show
				respond_with Announcement.find(params[:id])
			end
			def create
				respond_with Announcement.create(announcement_params)
			end
			def update
				respond_with Announcement.update(params[:id], announcement_params)
			end
			def destroy
				respond_with Announcement.destroy(params[:id])
			end
			private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:title, :description, :deadline, :tags)
    end
		end
	end
end

anunciar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

anunciar/app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    skip_before_filter :authenticate_user!, :only => [:create, :new]
    skip_authorization_check only: [:create, :failure, :show_current_user, :options, :new]
    respond_to :json

    def new
      self.resource = resource_class.new(sign_in_params)
      clean_up_passwords(resource)
      respond_with(resource, serialize_options(resource))
    end

    def create

      respond_to do |format|
        format.html {
          super
        }
        format.json {

          resource = resource_from_credentials
          #build_resource
          return invalid_login_attempt unless resource

          if resource.valid_password?(params[:password])
            render :json => { user: { email: resource.email, :auth_token => resource.authentication_token } }, success: true, status: :created
          else
            invalid_login_attempt
          end
        }
      end
    end

    def destroy
      respond_to do |format|
        format.html {
          super
        }
        format.json {
          user = User.find_by_authentication_token(request.headers['X-API-TOKEN'])
          if user
            user.reset_authentication_token!
            render :json => { :message => 'Session deleted.' }, :success => true, :status => 204
          else
            render :json => { :message => 'Invalid token.' }, :status => 404
          end
        }
      end
    end

    protected
    def invalid_login_attempt
      warden.custom_failure!
      render json: { success: false, message: 'Error with your login or password' }, status: 401
    end

    def resource_from_credentials
      data = { email: params[:email] }
      if res = resource_class.find_for_database_authentication(data)
        if res.valid_password?(params[:password])
          res
        end
      end
    end
  end

anunciar/app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

anunciar/app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
  		content_for :title, page_title.to_s
	end
end

anunciar/app/views/announcements/index.html.erb
<% title "Announcements" %>
<!-- Event card -->
<div class="mdl-grid">
<% @announcements.each do |announcement| %>
  <%= link_to announcement, :class => 'mdl-cell mdl-cell--12-col animated fadeInUp' do %>
  <div class="" >
    <div  class="demo-card-event mdl-card mdl-shadow--16dp" >
      <div class="mdl-card__title mdl-card--expand">
        <h4 style="text-align: center; font-size: 1.3rem; width: 100%; height: 100%; padding-top: 9%;">
          <%=announcement.title %>
        </h4>
      </div>
      <!-- <div class="mdl-card__actions mdl-card--border">
        
        <div class="mdl-layout-spacer"></div>
        <i class="material-icons">speaker_notes</i>
      </div> -->
    </div>
  </div>
  <% end %>
<% end %>
</div>

anunciar/app/views/announcements/show.html.erb
<% title @announcement.title[0..10]+'...' %>

<!-- Wide card with share menu button -->
<style>
  .demo-card-wide {
  width: 50%; 
  margin: 0 auto;
  margin-top: 50px;
}
@media screen and (max-width: 500px) {
    .demo-card-wide {
      width: 90%;

    }
}
</style>

<div class="demo-card-wide mdl-card mdl-shadow--2dp animated fadeInUp">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text"><%= @announcement.title %></h2>
  </div>
  <div class="mdl-card__supporting-text">
    <%= @announcement.description %>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <div class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
      <%= @announcement.deadline %>
    </div>
  </div>
  <div class="mdl-card__menu">
    <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect">
      <i class="material-icons"><%= link_to 'keyboard_arrow_left', root_path %></i>
    </button>
  </div>
</div>

anunciar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html manifest="/application.manifest">
	<head>
		<title>Anunciar</title>
			<%= csrf_meta_tags %>
			<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
			<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
			<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
			<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="manifest" href="/manifest.json" /></head>
	<body>
		<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
			<header class="mdl-layout__header">
				<div class="mdl-layout__header-row">
				<!-- Title -->
				<span class="mdl-layout-title"><%= yield(:title)%></span>
				<!-- Add spacer, to align navigation to the right -->
				<div class="mdl-layout-spacer"></div>
				<!-- Navigation. We hide it in small screens. -->
				<nav class="mdl-navigation mdl-layout--large-screen-only">
					<% if student_signed_in? %>
  						<%= link_to edit_student_registration_path, :class => 'mdl-navigation__link'  do %>
  							<i id="tt3" class="material-icons">account_circle</i>
  							<div class="mdl-tooltip" data-mdl-for="tt3">
							Logged in as <strong><%= current_student.email.split('@')[0] %></strong>
							</div>
  						<% end %>
  						 |
  						<%= link_to destroy_student_session_path, method: :delete, :class => 'mdl-navigation__link' do  %>
  							<i id="log_out" class="material-icons">remove_circle</i>
  							<div class="mdl-tooltip" data-mdl-for="log_out">
								Log out
							</div>
  						<% end %>
					<% else %>
  						<%= link_to "Login", new_student_session_path, :class => 'mdl-navigation__link'  %>
					<% end %>
				</nav>
				</div>
			</header>
			<div class="mdl-layout__drawer">
				<span class="mdl-layout-title"><%= yield(:title)%></span>
				<nav class="mdl-navigation">
					<% if student_signed_in? %>
  						<%= link_to edit_student_registration_path, :class => 'mdl-navigation__link'  do %>
  							<i id="tt3" class="material-icons">account_circle</i>
  							<span><%= current_student.email.split('@')[0] %></span>
  						<% end %>
  						 |
  						<%= link_to destroy_student_session_path, method: :delete, :class => 'mdl-navigation__link' do  %>
  							<i id="log_out" class="material-icons">remove_circle</i> <span>Log Out</span>
  						<% end %>
					<% else %>
  						<%= link_to "Login", new_student_session_path, :class => 'mdl-navigation__link'  %>
					<% end %>
				</nav>
			</div>
			<main class="mdl-layout__content">
				<% if notice %>
  					<p class="alert alert-success"><%= notice %></p>
				<% end %>
				<% if alert %>
  					<p class="alert alert-danger"><%= alert %></p>
				<% end %>
				<div class="page-content"><%= yield %></div>
			</main>
		</div>
	</body>
</html>